#FROM sharmaatul11/fsl502py369ltx-full:latest
#FROM sharmaatul11/yashengstep1withfsl:latest
#FROM yashengwustl/stroke_ct_segmentation:latest
FROM sharmaatul11/ct_segmentation_yasheng:latest
RUN apt update
#RUN mkdir -p /callfromgithub
#RUN chmod 755 /callfromgithub
##RUN chmod 777 /root/anaconda3/
##RUN chmod +x /root/anaconda3/envs/tf/bin/*
#COPY downloadcodefromgithub.sh /callfromgithub/
#RUN chmod +x /callfromgithub/downloadcodefromgithub.sh
#RUN chmod +x /Stroke_CT_Segmentation/*.sh
##RUN cp -r  /usr/share/fsl/5.0/* /usr/lib/fsl/5.0/
#RUN chmod 755 /Stroke_CT_Segmentation
#RUN for x in  /Stroke_CT_Segmentation/*/* ; do chmod +x $x ; done
#RUN for x in  /Stroke_CT_Segmentation/* ; do chmod +x $x ; done
#RUN apt install -y \
#  vim  \
#  zip  \
#  unzip  \
#  curl  \
#  git \
#  tree  \
#  python3-pip
# # software-properties-common
##RUN apt-get update
##RUN add-apt-repository ppa:deadsnakes/ppa -y
#RUN pip3 install \
#  nibabel  \
#  numpy  \
#  xmltodict  \
#  pandas  \
#  requests  \
#  pydicom  \
#  python-gdcm  \
#  glob2  \
#  scipy  \
#  pypng  \
#  PyGithub
##SHELL ["/bin/bash", "-i", "-c"]
##RUN conda install numpy
